### ISSUE TITLE
pkgconfig

### ISSUE THREAD

**Issue by janisozaur** [dimensio/libpng16-deb#5]
pkgconfig file is not supplied with this version.

**Comment by janisozaur** [comment]
I believe the correct pkgconfig file would look like so:
```
prefix=/usr/local
exec_prefix=${prefix}
libdir=${prefix}/lib/
includedir=${prefix}/include/libpng16

Name: libpng16
Description: Loads and saves PNG files
Version: 1.6.21
Libs: -L${libdir} -lpng16
Libs.private: -lz -lm 
Cflags: -I${includedir}
```
and should be located in `/usr/lib/<your arch>/pkgconfig/libpng16.pc`

**Comment by lovell** [comment]
Commit 429f5e8 should help, thanks for reporting.
